"""tool management and configuration

Revision ID: 15d36d2a4f40
Revises: 67c183630e38
Create Date: 2026-07-18 13:18:46.965093

Adds Phase 5's discovery/health-tracking columns to ``tools``
(``status``, ``health_status``, ``health_message``, ``last_checked_at``)
and its full configuration surface to ``tool_configurations``
(``working_directory``, ``custom_executable_path``, per-protocol proxies,
``rate_limit``, ``retries``, ``output_directory``, ``temp_directory``),
replacing the single generic ``proxy`` column with the three specific
ones the phase brief asks for (HTTP/HTTPS/SOCKS).

``status`` is added ``NOT NULL`` with no server default — safe because
both `tools` and `tool_configurations` are verified empty at the time
this migration was authored (no plugin has ever synced into the catalog
yet), so there is no existing row for the new column to be applied to.
Autogenerated and used as-is: every change here is a straightforward
column add/drop with no enum value-set changes on an existing column, so
none of Phase 3's hand-editing was needed.

KNOWN LIMITATION — ``downgrade()`` on the ``tools`` table hits the same
SQLite batch-mode limitation documented on the Phase 3 migration
(``67c183630e38``): dropping the two new ``Enum`` columns forces a
full-table rebuild, and SQLAlchemy's reflection of the existing
(auto-named, not naming-convention-named) CHECK constraints from the
`upgrade()`-time `add_column` calls cannot be correctly re-attached to a
temp table that no longer has those columns — verified by attempting it
directly: it raises ``OperationalError: no such column: health_status``
building `_alembic_tmp_tools`, and rolls back cleanly (confirmed via
``PRAGMA integrity_check`` afterward — no partial/orphaned state). As
before, ``upgrade()`` is the fully verified path (applied, re-verified
that invalid ``status``/``health_status`` values are rejected by the
database via a raw-SQL insert); the practical rollback path for this
single-user local app is restoring `data/app.db` from a backup, not
``alembic downgrade``.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15d36d2a4f40'
down_revision: Union[str, None] = '67c183630e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_directory', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('custom_executable_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('http_proxy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('https_proxy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('socks_proxy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rate_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('output_directory', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('temp_directory', sa.String(length=1024), nullable=True))
        batch_op.drop_column('proxy')

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('INSTALLED', 'MISSING', 'DISABLED', 'MISCONFIGURED', 'UNSUPPORTED_VERSION', name='toolstatus', native_enum=False, create_constraint=True, length=32), nullable=False))
        batch_op.add_column(sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'ERROR', name='toolhealthstatus', native_enum=False, create_constraint=True, length=16), nullable=True))
        batch_op.add_column(sa.Column('health_message', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_tools_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_status'))
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('health_message')
        batch_op.drop_column('health_status')
        batch_op.drop_column('status')

    with op.batch_alter_table('tool_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('temp_directory')
        batch_op.drop_column('output_directory')
        batch_op.drop_column('retries')
        batch_op.drop_column('rate_limit')
        batch_op.drop_column('socks_proxy')
        batch_op.drop_column('https_proxy')
        batch_op.drop_column('http_proxy')
        batch_op.drop_column('custom_executable_path')
        batch_op.drop_column('working_directory')

    # ### end Alembic commands ###
