"""nmap_scan_profiles_and_normalized_output

Revision ID: 63098bf45bce
Revises: a264a27eb29e
Create Date: 2026-07-18 22:46:36.979709

Phase 7: new ``assets``/``services``/``observations`` tables -- generic,
tool-agnostic normalized-output storage (not Nmap-specific columns bolted
onto ``tool_executions``), since a single execution can discover more than
one host (e.g. a CIDR target) and any future scanner plugin can populate
the same three tables. Deliberately separate from ``findings``: no
severity/CVSS/vulnerability judgment lives here, per this phase's explicit
"do not generate vulnerabilities" instruction.

``tool_executions`` gains ``profile_id``/``generated_command``/
``advanced_options`` so a job remembers which Scan Profile (data, not
code -- see ``backend/plugins/plugins/nmap/profiles/``) it was planned
with and the exact argv that was actually run, for audit/display. All
three are nullable: only tools with a profile system (Nmap, this phase)
ever populate them.

Autogenerated as-is, no hand edits needed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63098bf45bce'
down_revision: Union[str, None] = 'a264a27eb29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('mac_vendor', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('UP', 'DOWN', 'UNKNOWN', name='assetstate', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('os_accuracy', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['tool_executions.id'], name=op.f('fk_assets_execution_id_tool_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_ip_address'), ['ip_address'], unique=False)

    op.create_table('observations',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_observations_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['tool_executions.id'], name=op.f('fk_observations_execution_id_tool_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_execution_id'), ['execution_id'], unique=False)

    op.create_table('services',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', name='networkprotocol', native_enum=False, create_constraint=True, length=8), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', 'FILTERED', 'OPEN_FILTERED', 'CLOSED_FILTERED', 'UNFILTERED', name='portstate', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_services_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('generated_command', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('advanced_options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_column('advanced_options')
        batch_op.drop_column('generated_command')
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_asset_id'))

    op.drop_table('services')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_execution_id'))
        batch_op.drop_index(batch_op.f('ix_observations_asset_id'))

    op.drop_table('observations')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_ip_address'))
        batch_op.drop_index(batch_op.f('ix_assets_execution_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
