"""create core domain schema

Revision ID: d2bf6f4862f6
Revises: 
Create Date: 2026-07-17 21:40:21.718170
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2bf6f4862f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_settings'))
    )
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_settings_key'), ['key'], unique=True)

    op.create_table('assessments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.Enum('WEB_APPLICATION', 'NETWORK', 'API', 'MOBILE', 'CLOUD', 'WIRELESS', 'OTHER', name='assessmenttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', name='assessmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index('ix_assessments_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('tools',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('installation_path', sa.String(length=1024), nullable=True),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_timeout', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_name'), ['name'], unique=True)

    op.create_table('analyst_notes',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_analyst_notes_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyst_notes'))
    )
    with op.batch_alter_table('analyst_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_notes_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assessment_tools',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_tools_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_assessment_tools_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', 'tool_id', name=op.f('pk_assessment_tools'))
    )
    op.create_table('attachments',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_attachments_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('reports',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('PDF', 'HTML', 'MARKDOWN', 'JSON', name='reporttype', native_enum=False, length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_reports_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('targets',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('IP', 'CIDR', 'HOSTNAME', 'DOMAIN', 'URL', name='targettype', native_enum=False, length=16), nullable=False),
    sa.Column('target_value', sa.String(length=512), nullable=False),
    sa.Column('resolved_ip', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_targets_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index('uq_targets_assessment_id_target_value', ['assessment_id', 'target_value'], unique=True)

    op.create_table('tool_configurations',
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('proxy', sa.String(length=255), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('environment_json', sa.JSON(), nullable=True),
    sa.Column('arguments_json', sa.JSON(), nullable=True),
    sa.Column('wordlists_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_configurations_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_configurations')),
    sa.UniqueConstraint('tool_id', name=op.f('uq_tool_configurations_tool_id'))
    )
    op.create_table('tool_executions',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED', name='toolexecutionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('stdout_path', sa.String(length=1024), nullable=True),
    sa.Column('stderr_path', sa.String(length=1024), nullable=True),
    sa.Column('log_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_tool_executions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_tool_executions_target_id_targets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_executions_tool_id_tools'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_executions'))
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index('ix_tool_executions_assessment_id_status', ['assessment_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_target_id'), ['target_id'], unique=False)
        batch_op.create_index('ix_tool_executions_target_id_tool_id', ['target_id', 'tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_tool_id'), ['tool_id'], unique=False)

    op.create_table('findings',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Enum('CONFIRMED', 'HIGH', 'MEDIUM', 'LOW', name='findingconfidence', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(length=20), nullable=True),
    sa.Column('owasp', sa.String(length=20), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CONFIRMED', 'FALSE_POSITIVE', 'ACCEPTED_RISK', 'REMEDIATED', 'DUPLICATE', name='findingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name=op.f('ck_findings_cvss_score_range')),
    sa.ForeignKeyConstraint(['execution_id'], ['tool_executions.id'], name=op.f('fk_findings_execution_id_tool_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index('ix_findings_execution_id_severity', ['execution_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('raw_tool_outputs',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('XML', 'JSON', 'TXT', 'HTML', 'CSV', name='rawoutputformat', native_enum=False, length=8), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_path IS NOT NULL OR raw_text IS NOT NULL', name=op.f('ck_raw_tool_outputs_has_content')),
    sa.ForeignKeyConstraint(['execution_id'], ['tool_executions.id'], name=op.f('fk_raw_tool_outputs_execution_id_tool_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_tool_outputs'))
    )
    with op.batch_alter_table('raw_tool_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_tool_outputs_execution_id'), ['execution_id'], unique=False)

    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('source_tool', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_evidence'))
    )
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_evidence_finding_id'), ['finding_id'], unique=False)

    op.create_table('finding_references',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('reference_type', sa.Enum('CWE', 'OWASP', 'CAPEC', 'CVE', 'VENDOR_URL', 'DOCUMENTATION_URL', name='findingreferencetype', native_enum=False, length=32), nullable=False),
    sa.Column('reference_value', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_references_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_references'))
    )
    with op.batch_alter_table('finding_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_references_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index('uq_finding_references_finding_id_type_value', ['finding_id', 'reference_type', 'reference_value'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_references', schema=None) as batch_op:
        batch_op.drop_index('uq_finding_references_finding_id_type_value')
        batch_op.drop_index(batch_op.f('ix_finding_references_finding_id'))

    op.drop_table('finding_references')
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_evidence_finding_id'))

    op.drop_table('finding_evidence')
    with op.batch_alter_table('raw_tool_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_tool_outputs_execution_id'))

    op.drop_table('raw_tool_outputs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index('ix_findings_execution_id_severity')
        batch_op.drop_index(batch_op.f('ix_findings_execution_id'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))

    op.drop_table('findings')
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_tool_id'))
        batch_op.drop_index('ix_tool_executions_target_id_tool_id')
        batch_op.drop_index(batch_op.f('ix_tool_executions_target_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_status'))
        batch_op.drop_index('ix_tool_executions_assessment_id_status')
        batch_op.drop_index(batch_op.f('ix_tool_executions_assessment_id'))

    op.drop_table('tool_executions')
    op.drop_table('tool_configurations')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index('uq_targets_assessment_id_target_value')
        batch_op.drop_index(batch_op.f('ix_targets_assessment_id'))

    op.drop_table('targets')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_assessment_id'))

    op.drop_table('reports')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_assessment_id'))

    op.drop_table('attachments')
    op.drop_table('assessment_tools')
    with op.batch_alter_table('analyst_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_notes_assessment_id'))

    op.drop_table('analyst_notes')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_name'))

    op.drop_table('tools')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_assessments_status_created_at')
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_name'))

    op.drop_table('assessments')
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_settings_key'))

    op.drop_table('application_settings')
    # ### end Alembic commands ###
